name: Java CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    env: # Or as an environment variable
      BOT_TOKEN: ${{ secrets.DEPLOY_BOT_TOKEN }}
      TARGET_CHAT_IDS: "[487353090, -1001342632426]"
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      ARTIFACT: "target/moe-moe-secretary.jar"

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Set up JDK 11
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Install Python 3.7
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.7'

    - name: Install requirements
      run: python3 -m pip -q install -r .github/workflows/requirements.txt

    - name: Build with Maven
      run: mvn -q -ntp -B package

    - name: Maven build failed
      if: failure()
      run: python3 .github/workflows/deployer.py maven_build_failed

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "moe-moe-secretary.jar"
        path: "target/moe-moe-secretary.jar"

    - name: GitHub deploy failed
      if: failure()
      run: python3 .github/workflows/deployer.py github_deploy_failed

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v0.1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: New Moe Moe Secretary release
        draft: false
        prerelease: false
        files: target/moe-moe-secretary.jar

    - name: Deploy to Telegram
      run: python3 .github/workflows/deployer.py deploy_to_telegram

    - name: Telegram deploy failed
      if: failure()
      run: python3 .github/workflows/deployer.py telegram_deploy_failed
